cd pretrained_models/
mkdir zhirong
cd zhirong/
mkdir v10_base_mask08_1crops_droppath01_wd01
cd v10_base_mask08_1crops_droppath01_wd01
wget https://frontiers.blob.core.windows.net/pretraining/projects/pwc/v10_base_mask08_1crops_droppath01_wd01/amlt_results/current.pth.tar
cd ..
cd ..
cd ..